//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Cook : User
{
    public string transport
    {
        get;
        set;
    }

    public string PVGstatus
	{
		get;
		set;
	}

	public string hygieneStatus
	{
		get;
		set;
	}

	public string hygieneExpiryDate
	{
		get;
		set;
	}

	public string PVGIssueDate
	{
		get;
		set;
	}

    public Cook()
    {

    }

	public  Cook (string username, string password, string name, string address, string postCode, string phone, string foodPrefer, string transport, string statusPVG, string PVGIssueDate, string hygieneStatus, string hygieneExpiryDate)
	{
        this.userName = username;
        this.password = password;
        this.name = name;
        this.address = address;
        this.phone = phone;
        this.foodPreference = foodPrefer;
        this.transport = transport;
        this.hygieneStatus = hygieneStatus;
        this.hygieneExpiryDate = hygieneExpiryDate;
        this.PVGIssueDate = PVGIssueDate;
        this.PVGstatus = statusPVG;
        this.rating = 5;
        this.postCode = postCode;
	}

	public  bool isHygieneExpiring()
	{
		throw new System.NotImplementedException();
	}

}

