//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Eater : User
{
    public int numberMeals
    {
        get;
        set;
    }
    public Eater()
    {
        numberMeals = 0;
    }
	public  Eater (string username, string password, string name, string address, string postCode, string phone, string foodPrefer)
	{
        this.userName = username;
        this.password = password;
        this.name = name;
        this.address = address;
        this.phone = phone;
        this.foodPreference = foodPrefer;
        this.rating = 5;
        this.postCode = postCode;
        numberMeals = 0;
    }

}

