//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Manager : Administrator
{
    public Manager(String name, String phone, String username, String password, String postcodeArea) {
        this.name = name;
        this.phone = phone;
        this.username = username;
        this.password = password;
        this.postcodeArea = postcodeArea;
    }

    
}

