//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Review
{
	public string comment
	{
		get;
		set;
	}

	public Photo picture
	{
		get;
		set;
	}

	public int rating
	{
		get;
		set;
	}


    public Review(String com, int rat)
    {
        this.comment = com;
        this.rating = rat;

    }

    public Review(String comment, int rating, Photo picture)
    {
        this.comment = comment;
        this.rating = rating;
        this.picture = picture;
    }

}

