//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class User
{
	public string name
	{
		get;
		set;
	}

	public string address
	{
		get;
		set;
	}

    public string postCode
    {
        get;
        set;
    }

	public int rating
	{
		get;
		set;
	}

	public string phone
	{
		get;
		set;
	}
    public string foodPreference
    {
        get;
        set;
    }

    public string userName
	{
		get;
		set;
	}

	public string password
	{
		get;
		set;
	}


	public virtual IEnumerable<Notification> notifications
	{
		get;
		set;
	}

    public User()
    {

    }

	public virtual void calculateRating(int rating)
	{
        this.rating = (this.rating + rating) / 2;
	}

	public virtual void notify(string message, string username)
	{
		throw new System.NotImplementedException();
	}

}

