//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Administrator
{
	private string postcodeArea
	{
		get;
		set;
	}

	private string name
	{
		get;
		set;
	}

	private string phone
	{
		get;
		set;
	}

	private string username
	{
		get;
		set;
	}

	private string password
	{
		get;
		set;
	}

}

