//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Eater : User
{
	public virtual Eater register(string name, string address, string phone, string foodPrefer)
	{
		throw new System.NotImplementedException();
	}

}

