//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class MealSharers
{
	private IEnumerable<Meal> meals
	{
		get;
		set;
	}

	private IEnumerable<User> cooks
	{
		get;
		set;
	}

	private IEnumerable<Administrator> administrators
	{
		get;
		set;
	}

	private IEnumerable<User> eaters
	{
		get;
		set;
	}

	public virtual IEnumerable<User> users
	{
		get;
		set;
	}

	public virtual void registerCook()
	{
		throw new System.NotImplementedException();
	}

	public virtual void registerEater()
	{
		throw new System.NotImplementedException();
	}

	public virtual void registerAdministrator()
	{
		throw new System.NotImplementedException();
	}

	public virtual Eater listRecommendedEaters(Cook cook)
	{
		throw new System.NotImplementedException();
	}

	public virtual void offerMeal(Cook cook, Eater eater, string date)
	{
		throw new System.NotImplementedException();
	}

	public virtual void writeReviewCook(Meal meal)
	{
		throw new System.NotImplementedException();
	}

	public virtual void writeReviewEater()
	{
		throw new System.NotImplementedException();
	}

	public virtual Meal listMeals()
	{
		throw new System.NotImplementedException();
	}

	public virtual void generateQuarterlyReport()
	{
		throw new System.NotImplementedException();
	}

	public virtual void ShowVolunteerMap()
	{
		throw new System.NotImplementedException();
	}

	public virtual void listCookCriticalReviews()
	{
		throw new System.NotImplementedException();
	}

	public virtual void listEatersSatisfactionRating()
	{
		throw new System.NotImplementedException();
	}

	public virtual void requestPVGcheck(Cook cook)
	{
		throw new System.NotImplementedException();
	}

	public virtual void requestHygieneCertification(Cook cook)
	{
		throw new System.NotImplementedException();
	}

	public virtual void approveCook(Cook cook)
	{
		throw new System.NotImplementedException();
	}

}

