//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class PVGrecord
{
	private string status
	{
		get;
		set;
	}

	private string issueDate
	{
		get;
		set;
	}

}

