//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Review
{
	private string comment
	{
		get;
		set;
	}

	private Photo picture
	{
		get;
		set;
	}

	private int rating
	{
		get;
		set;
	}

	public virtual Photo Photo
	{
		get;
		set;
	}

}

