//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class User
{
	private string name
	{
		get;
		set;
	}

	private string address
	{
		get;
		set;
	}

	private int rating
	{
		get;
		set;
	}

	private string phone
	{
		get;
		set;
	}

	private string userName
	{
		get;
		set;
	}

	private string password
	{
		get;
		set;
	}

	private IEnumerable<string> notifications
	{
		get;
		set;
	}

	public virtual IEnumerable<Notification> notifications
	{
		get;
		set;
	}

	public virtual void calculateRating(int rating)
	{
		throw new System.NotImplementedException();
	}

	public virtual void notify(string message, string username)
	{
		throw new System.NotImplementedException();
	}

}

